RiderPitStop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RiderPitStop.Models;
using RiderPitStop.Services;

namespace RiderPitStop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }



        public async Task<IActionResult> Tire()
        {
            var tireProducts = await _context.Products
                .Where(p => p.ProductCategory == Product.Category.Tire)
                .ToListAsync();
            return View("Index", tireProducts);
        }

        // GET: Products/Accessory
        public async Task<IActionResult> Accessory()
        {
            var accessoryProducts = await _context.Products
                .Where(p => p.ProductCategory == Product.Category.Accessory)
                .ToListAsync();
            return View("Index", accessoryProducts);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,Description,SRP,DP,Type,StockQuantity,Brand,ProductCategory")] Product product)
        {

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,Description,SRP,DP,Type,StockQuantity,Brand,ProductCategory")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

RiderPitStop/Controllers/RequestOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RiderPitStop.Models;
using RiderPitStop.Services;
using System.Collections.Generic;
using System.Linq;


namespace RiderPitStop.Controllers
{
    public class RequestOrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RequestOrderController(ApplicationDbContext context)
        {
            _context = context;
        }




        public IActionResult CompleteList()
        {
            var requestOrders = _context.RequestOrders
          .Include(ro => ro.Product)
          .Include(ro => ro.requestDetails)
          .Where(ro => ro.requestDetails.IsComplete)
          .ToList();

            return View(requestOrders);
        }

        public IActionResult Index()
        {
            var requestOrders = _context.RequestOrders
           .Include(ro => ro.Product)
           .Include(ro => ro.requestDetails)
           .Where(ro => !ro.requestDetails.IsComplete)
           .ToList();

            return View(requestOrders);
        }

        // Display the create request order form
        // Display the create request order form
        public IActionResult Create()
        {
            // Retrieve the logged-in user's username
            var username = User.Identity.Name;

            if (!string.IsNullOrEmpty(username))
            {
                // Assuming you have a Users table that includes FirstName and LastName
                var user = _context.Users.FirstOrDefault(u => u.Username == username);
                if (user != null)
                {
                    // Construct the "Prepared By" field using the user's first and last name
                    ViewBag.PreparedBy = $"{user.FirstName} {user.LastName}";
                }

            }


            ViewBag.Products = _context.Products.ToList(); // Load all products for selection

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DateTime dateTime, string note, int[] productIds, int[] quantities)
        {
            // Retrieve the logged-in user's username
            var username = User.Identity.Name;
            var preparedBy = "Unknown User";

            if (!string.IsNullOrEmpty(username))
            {
                var user = _context.Users.FirstOrDefault(u => u.Username == username);
                if (user != null)
                {
                    preparedBy = $"{user.FirstName} {user.LastName}";
                }
            }

            if (ModelState.IsValid)
            {
                // Create the RequestDetails entity
                var requestDetails = new RequestDetails
                {
                    PreparedBy = preparedBy, // Automatically populated based on logged-in user
                    DateTime = dateTime,
                    Note = note
                };

                // Save RequestDetails first to get DetailsId
                _context.RequestDetails.Add(requestDetails);
                _context.SaveChanges();

                // Consolidate quantities by ProductId
                var productQuantityMap = new Dictionary<int, int>();

                for (int i = 0; i < productIds.Length; i++)
                {
                    if (productQuantityMap.ContainsKey(productIds[i]))
                    {
                        productQuantityMap[productIds[i]] += quantities[i];
                    }
                    else
                    {
                        productQuantityMap[productIds[i]] = quantities[i];
                    }
                }

                // Add or update RequestOrder entries
                foreach (var entry in productQuantityMap)
                {
                    var productId = entry.Key;
                    var quantity = entry.Value;

                    var existingRequestOrder = _context.RequestOrders
                        .AsNoTracking()
                        .FirstOrDefault(ro => ro.ProductId == productId && ro.DetailsId == requestDetails.DetailsId);

                    if (existingRequestOrder == null)
                    {
                        var requestOrder = new RequestOrder
                        {
                            ProductId = productId,
                            DetailsId = requestDetails.DetailsId,
                            Quantity = quantity
                        };
                        _context.RequestOrders.Add(requestOrder);
                    }
                    else
                    {
                        existingRequestOrder.Quantity += quantity;
                        _context.RequestOrders.Update(existingRequestOrder);
                    }
                }

                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Products = _context.Products.ToList();
            return View();
        }




        public IActionResult CompleteDetails(int id)
        {
            var requestDetails = _context.RequestDetails
                .Include(rd => rd.RequestOrders) // Load associated RequestOrders
                    .ThenInclude(ro => ro.Product) // Load associated Products
                .FirstOrDefault(rd => rd.DetailsId == id);

            if (requestDetails == null)
            {
                return NotFound();
            }

            return View(requestDetails);
        }

        public IActionResult Details(int id)
        {
            var requestDetails = _context.RequestDetails
                .Include(rd => rd.RequestOrders) // Load associated RequestOrders
                    .ThenInclude(ro => ro.Product) // Load associated Products
                .FirstOrDefault(rd => rd.DetailsId == id);

            if (requestDetails == null)
            {
                return NotFound();
            }

            return View(requestDetails);
        }



        [HttpPost]
        public IActionResult MarkAsComplete(int detailsId)
        {
            var requestDetails = _context.RequestDetails
                .Include(rd => rd.RequestOrders)
                .ThenInclude(ro => ro.Product)
                .FirstOrDefault(rd => rd.DetailsId == detailsId);

            if (requestDetails != null)
            {
                try
                {
                    // Mark the request as complete
                    requestDetails.IsComplete = true;

                    // Update the product stock quantities based on the RequestOrders
                    foreach (var requestOrder in requestDetails.RequestOrders)
                    {
                        var product = requestOrder.Product;

                        if (product != null)
                        {
                            // Increment StockQuantity by the request order quantity
                            product.StockQuantity = (product.StockQuantity ?? 0) + requestOrder.Quantity;
                        }
                    }

                    // Save changes to the database
                    _context.SaveChanges();
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error updating stock quantities: {ex.Message}");
                    // Optionally, handle the error here, such as by returning an error view or logging the error.
                }
            }

            return RedirectToAction(nameof(Index));
        }




    }
}

RiderPitStop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RiderPitStop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RiderPitStop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RiderPitStop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RequestOrder" asp-action="Create">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Create">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Tire">Tire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Accessory">Accessory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RiderPitStop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RiderPitStop/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonsTiendaCebu</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonsTiendaCebu</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> <!-- Font Awesome CDN -->

    <style>
        body {
            margin: 0;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #1e1e2f; /* Dark background color */
        }

        .login-container {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background: white;
            border-radius: 10px; /* Rounded corners for a modern feel */
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
            text-align: center; /* Center the text */
        }

        /* Additional styles go here */

    </style>
</head>
<body>
    <div class="login-container">
        @RenderBody() <!-- This must be included to render the content of the view -->
    </div>
</body>
</html>